output "id" {
  value       = "${aws_db_instance.default.id}"
  description = "The database instance ID"
}

output "hosted_zone_id" {
  value       = "${aws_db_instance.default.hosted_zone_id}"
  description = "The zone ID for the autogenerated DNS name given in endpoint"
}

output "hostname" {
  value       = "${aws_db_instance.default.address}"
  description = "Public DNS name of database instance"
}

output "port" {
  value       = "${aws_db_instance.default.port}"
  description = "Port of database instance"
}

output "endpoint" {
  value       = "${aws_db_instance.default.endpoint}"
  description = "Public DNS name and port separated by a colon"
}